### ISSUE TITLE
why synset.labels.list is diffrerent imagenet.labels.list 

### ISSUE THREAD

**Issue by azuryl** [WePCf/darknet-mobilenet-v2#2]
so valid list build by  pjreddie.commothod  can not be used

**Comment by azuryl** [comment]
I have  verifed if I use the imagenet.labels.list the "VALID" process will failed if use your label list it will success. two label file have some different in content.

**Comment by WePCf** [comment]
The original darknet's "imagenet.labels.list" is different from "sysnet.labels.list". More precisely, the order of the class label must be the same to the pretrained weights.

**Comment by azuryl** [comment]
thank you
