### ISSUE TITLE
the effect between relu and relu6

### ISSUE THREAD

**Issue by wxhqw** [WePCf/darknet-mobilenet-v2#7]
have you ever tried the relu6 , there is big difference between the relu6 and relu?

**Comment by WePCf** [comment]
I didn't try it. Sorry

**Comment by wxhqw** [comment]
thanks

**Comment by aditbhrgv** [comment]
Hi wxhqw,

I want to try Relu6 for darknet implementation instead of Leaky relu.
I am also trying Relu activation.

I am wondering if you already have the code of Relu6 for Darknet C implementation implemented in your repository ?

If yes, can you please share that ?

THanks
